In [1]:
import numpy as np

In [2]:
arr_2d = np.array([[5,10,5],
                   [20,25,30],
                   [35,40,45]
                  ])

In [3]:
arr_2d[0][0]

5

In [4]:
arr_2d[1][1]

25

In [6]:
arr_2d[2,1]

40

In [7]:
arr_2d[2][1]

40

:2: Selects the first two rows (row indices 0 and 1).
1:: Selects all columns starting from the second column (column index 1 to the end).

In [11]:
arr_2d[:2,1:]

array([[10,  5],
       [25, 30]])

In [13]:
arr_2d[:3,1:]

array([[10,  5],
       [25, 30],
       [40, 45]])

In [19]:
arr_2d[:2,0:2]

array([[ 5, 10],
       [20, 25]])

In [20]:
arr_2d[:2]

array([[ 5, 10,  5],
       [20, 25, 30]])

In [21]:
arr_2d[:3]

array([[ 5, 10,  5],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
arr= np.arange(1,11)

In [24]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [28]:
bool_arr=arr>5

In [29]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [30]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [31]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [32]:
arr[arr<3]

array([1, 2])

In [33]:
arr_2d=np.arange(50).reshape(5,10)

In [34]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [35]:
arr_2d[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [36]:
arr_2d[:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [39]:
arr_2d[1:3,]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [38]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [42]:
arr_2d[1:4,3:6]

array([[13, 14, 15],
       [23, 24, 25],
       [33, 34, 35]])