# __Indexing__

## __Agenda__
In this lesson, we will cover the following concepts with the help of examples:

- NumPy Array Indexing
  * Access Elements in the 1D NumPy Array
  * Access Elements in the 2D NumPy Array
  * Access Elements in 3D NumPy Array
  * Negative Indexing

## __1. NumPy Array Indexing__ ##
NumPy indexing allows you to access an array element using an index value, which begins from 0.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/4_Indexing/Image_1.png)

In [1]:
# Let's create 1D, 2D and 3D NumPy arrays:
import numpy as np
array_1d = np.array([1,2,3,4,5,6])
array_2d = np.array([[1,2,3],[4,5,6]])
array_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

### __1.1 Access Elements in the 1D NumPy Array__ ###

In [3]:
print(array_1d)

[1 2 3 4 5 6]


In [5]:
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [7]:
print(array_3d)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [13]:
print(array_3d[1,1,1])

11


In [ ]:
# Print the value of index 3
print(array_1d[3])

4


In [15]:
# Print the addition of indexes 0 and 1
print(array_1d[1] + array_1d[0])

3


### __1.2 Access Elements in the 2D NumPy Array__
Consider a 2D array as a table, with dimensions as rows and indexes as columns.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/4_Indexing/Image_2.png)

In [18]:
# Print third element of the first row of a 2D array
print('3rd element on 1st row: ', array_2d[0, 2])

3rd element on 1st row:  3


In [20]:
# Print second element of the second row of a 2D array
print('2nd element on 2nd row: ', array_2d[1, 1])

2nd element on 2nd row:  5


### __1.3 Access Elements in 3D NumPy Array__ ###
- [x,y,z] corresponds to xth element, yth row, and zth column.

In [ ]:
# Print the first element of the second array
print(array_3d[1, 1, 0])

10


### __1.4 Negative Indexing__

- Negative indices are counted from the end of an array.
- In a negative indexing system, the last element will be the first element with an index of -1, the second last element with an index of -2, and so on.

In [22]:
 # Print the fourth element of the 1D array using negative indexing
print(array_1d[-3])

4


In [ ]:
# Print the last element of the 2D array using negative indexing
print(array_2d[1,-1])

6


In [27]:
# Print the last element of the 3D array using negative indexing
print(array_3d)
print(array_3d[1,1,-1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
12


## __Assisted Practice__

### __Problem Statement:__

1. Create a 1D NumPy array with at least 10 elements
2. Create a 2D NumPy array with a minimum of 3 rows and 4 columns
3. Create a 3D NumPy array with at least 2 matrices, each containing 2 rows and 3 columns
4. Accessing Elements in Arrays
5. Access and print various elements from 1D, 2D, and, 3D using positive indexing
6. Perform and print some basic arithmetic operations (like addition, subtraction) using elements accessed from 1D, 2D, and, 3D arrays
7. Access and print elements using negative indices in all three arrays

In [1]:
import numpy as np

# 1. Create a 1D NumPy array with at least 10 elements
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("1D Array:")
print(arr_1d)



1D Array:
[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# 2. Create a 2D NumPy array with a minimum of 3 rows and 4 columns
arr_2d = np.array([[11, 12, 13, 14],
                    [15, 16, 17, 18],
                    [19, 20, 21, 22]])
print("\n2D Array:")
print(arr_2d)




2D Array:
[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]


In [5]:
# 3. Create a 3D NumPy array with at least 2 matrices, each containing 2 rows and 3 columns
arr_3d = np.array([[[23, 24, 25], [26, 27, 28]],
                    [[29, 30, 31], [32, 33, 34]]])
print("\n3D Array:")
print(arr_3d)




3D Array:
[[[23 24 25]
  [26 27 28]]

 [[29 30 31]
  [32 33 34]]]


In [13]:
# 4. Accessing Elements in Arrays
# Accessing elements using positive indices
print("\nAccessing elements using positive indices:")
print("-------------------------")
print("Element at index 3 in 1D array:", arr_1d[3])
print("-------------------------")
print("Element at row 2, column 1 in 2D array:", arr_2d[2, 1])
print("-------------------------")
print("Element at matrix 1, row 1, column 2 in 3D array:", arr_3d[1, 1, 2])




Accessing elements using positive indices:
-------------------------
Element at index 3 in 1D array: 4
-------------------------
Element at row 2, column 1 in 2D array: 20
-------------------------
Element at matrix 1, row 1, column 2 in 3D array: 34


In [15]:
# 5. Perform and print some basic arithmetic operations
sum_result = arr_1d[2] + arr_2d[1, 2] + arr_3d[0, 1, 1]
sub_result = arr_1d[5] - arr_2d[0, 3] - arr_3d[1, 0, 2]
print("\nArithmetic operations:")
print("-------------------------")
print("Sum of selected elements:", sum_result)
print("-------------------------")
print("Subtraction of selected elements:", sub_result)




Arithmetic operations:
-------------------------
Sum of selected elements: 47
-------------------------
Subtraction of selected elements: -39


In [17]:
# 6. Accessing elements using negative indices
print("\nAccessing elements using negative indices:")
print("-------------------------")
print("Last element in 1D array:", arr_1d[-1])
print("-------------------------")
print("Element at last row, second last column in 2D array:", arr_2d[-1, -2])
print("-------------------------")
print("Element at last matrix, last row, last column in 3D array:", arr_3d[-1, -1, -1])



Accessing elements using negative indices:
-------------------------
Last element in 1D array: 10
-------------------------
Element at last row, second last column in 2D array: 21
-------------------------
Element at last matrix, last row, last column in 3D array: 34
