# __Slicing__

## __Agenda__
In this lesson, we will cover the following concepts with the help of examples:

- NumPy Array Slicing
  * Slicing 1D NumPy Arrays
  * Slicing Using Step Value
  * Slicing: 2D Array
  * Slicing: 3D Array
  * Negative Slicing

## __1. NumPy Array Slicing__

- In Python, slicing refers to moving elements from one index to another.
- Instead of using an index, the slice is passed as **[start:end]**.
- Another way to pass the slice is to add a step as **[start:end:step]**.
- In slicing, if the starting is not passed, it is considered as 0. If the step is not passed as 1 and if the end is not passed, it is considered as the length of the array in that dimension.

### __1.1 Slicing 1D NumPy Arrays__

#### Example 1: Use slicing to retrieve employee ratings for a team of seven employees in the first quarter from an array

In [33]:
import numpy as np
Employee_rating = np.array([1, 4, 3, 5, 6, 8, 9, 10, 12])
print("-------------------------")
print(Employee_rating[1:7])

-------------------------
[4 3 5 6 8 9]


#### Example 2: Print the list of three subjects from the fourth index to the end

In [27]:
Books = np.array(['Physics','DataScience','Maths','Python','Hadoop', 'OPPs', 'Java', 'Cloud'])
print("-------------------------")
print(Books[5:])

-------------------------
['OPPs' 'Java' 'Cloud']


### __1.2 Slicing Using Step Value__

In [25]:
X = np.array([8, 7, 6, 5, 4, 3, 2, 1])
print(X)
print("-------------------------")
print(X[1:6:3])

[8 7 6 5 4 3 2 1]
-------------------------
[7 4]


### __1.3 Slicing: 2D Array__

In [23]:
Z = np.array([[11, 22, 33, 44, 55],
              [66, 77, 88, 99, 110]])
print(Z)
print("-------------------------")
print(Z[0, 2:3])

[[ 11  22  33  44  55]
 [ 66  77  88  99 110]]
-------------------------
[33]


### __1.4 Slicing: 3D Array__

In [21]:
array_3d = np.array([[[1,2,3],
                      [4,5,6]],
                     [[7,8,9],
                      [10,11,12]]])
print(array_3d)
print("-------------------------")
print(array_3d[0,1:,1:])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
-------------------------
[[5 6]]


### __1.5 Negative Slicing__
- Negative slicing is the same as negative indexing, which is interpreted as counting from the end of an array.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/5_Slicing/Image_1.png)

In [12]:
# Negative slicing for 1D array
Neg_slice = np.array([13, 34, 58, 69, 44, 56, 37,24])
print(Neg_slice[:-1])

[13 34 58 69 44 56 37]


## __Assisted Practice__

### __Problem Statement:__

- Creating arrays for slicing:
  * Create a 1D NumPy array with at least 15 elements
  * Create a 2D NumPy array with a minimum of 4 rows and 5 columns
  * Create a 3D NumPy array with at least 2 matrices, each containing 3 rows and 4 columns

- Slicing 1D arrays:
  * Perform and demonstrate different slices on the 1D array, explore it using step values

- Slicing 2D arrays:
  * Slice rows and columns separately and in combination

- Slicing 3D arrays:
  * Perform slicing to access different matrices, rows within matrices, and elements within rows

- Negative slicing:
  * Implement negative slicing on 1D, 2D, and 3D arrays
  * Compare the outcomes of negative slicing with positive slicing

In [15]:
import numpy as np

# Creating a 1D NumPy array with at least 15 elements
array_1d = np.arange(1, 16)
print("1D Array:")
print(array_1d)



1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [17]:
# Creating a 2D NumPy array with a minimum of 4 rows and 5 columns
array_2d = np.arange(1, 21).reshape(4, 5)
print("\n2D Array:")
print(array_2d)



2D Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [51]:
# Creating a 3D NumPy array with at least 2 matrices, each containing 3 rows and 4 columns
array_3d = np.arange(1, 25).reshape(2, 3, 4)
print("\n3D Array:")
print(array_3d)




3D Array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [57]:
# Slicing 1D Array
print("\nSlicing 1D Array:")

print("-------------------------")
print("First 5 elements:", array_1d[:5])

print("-------------------------")
print("Last 5 elements:", array_1d[-5:])

print("-------------------------")
print("Every 2nd element:", array_1d[::2])

print("-------------------------")
print("Reverse array:", array_1d[::-1])




Slicing 1D Array:
-------------------------
First 5 elements: [1 2 3 4 5]
-------------------------
Last 5 elements: [11 12 13 14 15]
-------------------------
Every 2nd element: [ 1  3  5  7  9 11 13 15]
-------------------------
Reverse array: [15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [59]:
# Slicing 2D Array
print("\nSlicing 2D Array:")
print("-------------------------")
print("First 2 rows:\n", array_2d[:2, :])
print("-------------------------")
print("Last 2 columns:\n", array_2d[:, -2:])
print("-------------------------")
print("Middle 2x3 subarray:\n", array_2d[1:3, 1:4]
     )




Slicing 2D Array:
-------------------------
First 2 rows:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
-------------------------
Last 2 columns:
 [[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]]
-------------------------
Middle 2x3 subarray:
 [[ 7  8  9]
 [12 13 14]]


In [61]:
# Slicing 3D Array
print("\nSlicing 3D Array:")
print("-------------------------")
print("First matrix:\n", array_3d[0])
print("-------------------------")
print("Second row of first matrix:\n", array_3d[0, 1, :])
print("-------------------------")
print("Last two columns of second matrix:\n", array_3d[1, :, -2:])




Slicing 3D Array:
-------------------------
First matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-------------------------
Second row of first matrix:
 [5 6 7 8]
-------------------------
Last two columns of second matrix:
 [[15 16]
 [19 20]
 [23 24]]


In [63]:
# Negative Slicing
print("\nNegative Slicing:")
print("-------------------------")
print("Last 5 elements of 1D array:", array_1d[-5:])
print("-------------------------")
print("Last row of 2D array:\n", array_2d[-1, :])
print("-------------------------")
print("Last matrix of 3D array:\n", array_3d[-1])



Negative Slicing:
-------------------------
Last 5 elements of 1D array: [11 12 13 14 15]
-------------------------
Last row of 2D array:
 [16 17 18 19 20]
-------------------------
Last matrix of 3D array:
 [[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
