<a href="https://colab.research.google.com/github/aishwaryasgh/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [7]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
type(arr)

numpy.ndarray

In [9]:
arr.ndim

1

In [11]:
arr0 = np.array([])

In [12]:
arr0.ndim

1

In [13]:
arr0.shape

(0,)

In [14]:
arr.shape

(10,)

In [15]:
len(arr)

10

In [16]:
len(arr0)

0

In [19]:
arr.dtype

dtype('int64')

In [20]:
arr0.dtype

dtype('float64')

NumPy defaults to `float64` for empty arrays because:  

1. **General-purpose default**: `float64` is a commonly used numerical data type that can handle both integers and floating-point numbers without losing precision (for most cases).  

2. **Avoiding unintended integer division issues**: Since division in Python and NumPy often results in floats, using `float64` prevents potential issues when performing calculations on an array.  

3. **Consistency with NumPy’s behavior**: NumPy assigns `float64` when it cannot infer the type from the data. Since an empty array has no elements, NumPy picks `float64` as a safe and flexible default.  

You can always override this default by specifying a data type explicitly:  
```python
arr_int = np.array([], dtype=int)  # Empty array with integer dtype
print(arr_int.dtype)  # Output: int64 (or int32 depending on the system)
```

In [21]:
arrint = np.array([],dtype=int)

In [22]:
arrint.dtype

dtype('int64')

In [25]:
arr1d = np.arange(10)

In [26]:
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
print(arr1d)

[0 1 2 3 4 5 6 7 8 9]


In [29]:
%time for _ in range(10): arr1d = arr1d * 2

CPU times: user 274 µs, sys: 30 µs, total: 304 µs
Wall time: 598 µs


In [32]:
%time for _ in range(10): arr1d = [x * 2 for x in arr1d]


CPU times: user 54 µs, sys: 0 ns, total: 54 µs
Wall time: 58.7 µs
