In [1]:
my_list=[1,2,3]

In [2]:
my_list

[1, 2, 3]

In [2]:
import numpy as np

In [5]:
#is used to convert a Python list (my_list) into a NumPy array (arr) using the numpy library. 
arr=np.array(my_list)

In [21]:
arr

array([1, 2, 3])

In [22]:
#The variable my_mat is a 2D list (or matrix) in Python. It is essentially a list of lists, where:
#The outer list contains three inner lists.
#Each inner list represents a row in the matrix.

my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [23]:
#is used to create a NumPy array newarr from an existing list of lists or nested lists stored in my_mat.
newarr=np.array(my_mat)

In [9]:
newarr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
#np.arange(start, stop, step):

#start: The starting value of the sequence (inclusive). Here, it's 0.
#stop: The ending value of the sequence (exclusive). Here, it's 10.
#step: The step size or spacing between values (optional; default is 1).
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(4)

array([0., 0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

np.linspace(0,5,100)
It looks like you're using the linspace function from NumPy in Python! This function is handy when you need to create arrays with evenly spaced numbers over a specified range.

Here's what np.linspace(0,5,100) does:

0 is the starting value of the sequence.

5 is the ending value of the sequence.

100 is the number of samples to generate between 0 and 5 (inclusive).

So, np.linspace(0,5,100) creates an array of 100 evenly spaced numbers starting from 0 to 5
np.linspace(0,5,100)

In [3]:
np.random.rand(5)

array([0.89759675, 0.71232223, 0.30135098, 0.33718787, 0.44120036])

In [4]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
np.random.rand(5)

array([0.26425717, 0.9629997 , 0.85457466, 0.41618742, 0.92685798])

In [7]:
np.random.rand(5,5)

array([[0.07774825, 0.2321395 , 0.53132389, 0.28777485, 0.74525444],
       [0.4989654 , 0.11299584, 0.43499444, 0.28826908, 0.06805778],
       [0.20265536, 0.80383429, 0.56203041, 0.8095765 , 0.19868452],
       [0.73307174, 0.35159891, 0.24786014, 0.41780866, 0.3880282 ],
       [0.04656486, 0.37795839, 0.085672  , 0.92756699, 0.57761432]])

In [8]:
np.random.randn(2)

array([ 0.97657814, -0.78048569])

In [9]:
np.random.randn(4,4)

array([[-0.46435532, -0.82233833,  0.47332316,  2.60638645],
       [-0.76532694,  1.66136721,  1.74377248,  0.99611451],
       [-0.06494256, -0.34412739,  1.86646846,  1.48443517],
       [-0.65482212,  0.72563785, -0.37709278, -0.90363667]])

In [14]:
np.random.randint(1,100)

79

In [15]:
np.random.randint(1,100,10)

array([45, 85, 11, 82, 87, 30, 89, 17,  3, 83])

In [17]:
arr=np.arange(25)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
ranarr=np.random.randint(0,50,10)

In [22]:
ranarr

array([ 9, 25, 19, 20, 16, 41, 48, 25, 25, 40])

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
ranarr.max()

48

In [26]:
ranarr.min()

9

In [27]:
ranarr.argmax()

6

In [28]:
ranarr.argmin()

0

In [30]:
arr.shape


(25,)

In [31]:
ranarr.shape

(10,)

In [32]:
arr=arr.reshape(5,5)

In [33]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
arr.dtype

dtype('int32')

In [35]:
np.random.randint(1,100,10)

array([54, 43, 79, 81, 12,  8, 86, 29, 51, 39])

In [39]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
ranarr.max()

48

In [41]:
ranarr.min()

9

In [42]:
ranarr

array([ 9, 25, 19, 20, 16, 41, 48, 25, 25, 40])

In [43]:
ranarr.argmax()

6

In [44]:
ranarr.argmin()

0

In [46]:
arr.shape

(5, 5)

In [47]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
arr.shape

(5, 5)

In [50]:
arr.dtype

dtype('int32')

In [51]:
from numpy.random import randint

In [52]:
randint(2,10)

9